<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 8 Regression |  Intro to R Workshop</title>
  <meta name="description" content="This is a book created for the CHI workshop on R for data analysis." />
  <meta name="generator" content="bookdown 0.32 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 8 Regression |  Intro to R Workshop" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is a book created for the CHI workshop on R for data analysis." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 8 Regression |  Intro to R Workshop" />
  
  <meta name="twitter:description" content="This is a book created for the CHI workshop on R for data analysis." />
  

<meta name="author" content="Dr. Na Li, Mark Ly" />


<meta name="date" content="2023-04-28" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="data-visualization.html"/>
<link rel="next" href="other-capabilties.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">CHI R Workshop 2023 - Intro to R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> About the workshop</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#audience"><i class="fa fa-check"></i><b>1.1</b> Audience</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#learning-objectives"><i class="fa fa-check"></i><b>1.2</b> Learning objectives</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="r-and-r-studio.html"><a href="r-and-r-studio.html"><i class="fa fa-check"></i><b>2</b> R and R studio</a>
<ul>
<li class="chapter" data-level="2.1" data-path="r-and-r-studio.html"><a href="r-and-r-studio.html#getting-started-desktop"><i class="fa fa-check"></i><b>2.1</b> Getting Started (Desktop)</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="r-and-r-studio.html"><a href="r-and-r-studio.html#installation"><i class="fa fa-check"></i><b>2.1.1</b> Installation</a></li>
<li class="chapter" data-level="2.1.2" data-path="r-and-r-studio.html"><a href="r-and-r-studio.html#creating-a-project"><i class="fa fa-check"></i><b>2.1.2</b> Creating a Project</a></li>
<li class="chapter" data-level="2.1.3" data-path="r-and-r-studio.html"><a href="r-and-r-studio.html#creating-.rmd-file"><i class="fa fa-check"></i><b>2.1.3</b> Creating .RMD file</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="r-and-r-studio.html"><a href="r-and-r-studio.html#getting-started-cloud"><i class="fa fa-check"></i><b>2.2</b> Getting Started (Cloud)</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="r-and-r-studio.html"><a href="r-and-r-studio.html#creating-.rmd-file-1"><i class="fa fa-check"></i><b>2.2.1</b> Creating .RMD File</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="basics.html"><a href="basics.html"><i class="fa fa-check"></i><b>3</b> Basics</a>
<ul>
<li class="chapter" data-level="3.1" data-path="basics.html"><a href="basics.html#basic-operations"><i class="fa fa-check"></i><b>3.1</b> Basic Operations</a></li>
<li class="chapter" data-level="3.2" data-path="basics.html"><a href="basics.html#code-chunk"><i class="fa fa-check"></i><b>3.2</b> Code Chunk</a></li>
<li class="chapter" data-level="3.3" data-path="basics.html"><a href="basics.html#storing-variables"><i class="fa fa-check"></i><b>3.3</b> Storing Variables</a></li>
<li class="chapter" data-level="3.4" data-path="basics.html"><a href="basics.html#using-variables"><i class="fa fa-check"></i><b>3.4</b> Using Variables</a></li>
<li class="chapter" data-level="3.5" data-path="basics.html"><a href="basics.html#logical-operators"><i class="fa fa-check"></i><b>3.5</b> Logical operators</a></li>
<li class="chapter" data-level="3.6" data-path="basics.html"><a href="basics.html#data-types"><i class="fa fa-check"></i><b>3.6</b> Data types</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data-structures.html"><a href="data-structures.html"><i class="fa fa-check"></i><b>4</b> Data Structures</a>
<ul>
<li class="chapter" data-level="4.1" data-path="data-structures.html"><a href="data-structures.html#vectors"><i class="fa fa-check"></i><b>4.1</b> Vectors</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="data-structures.html"><a href="data-structures.html#creating-simple-vectors"><i class="fa fa-check"></i><b>4.1.1</b> Creating simple vectors</a></li>
<li class="chapter" data-level="4.1.2" data-path="data-structures.html"><a href="data-structures.html#simple-vector-operations"><i class="fa fa-check"></i><b>4.1.2</b> Simple vector operations</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="data-structures.html"><a href="data-structures.html#lists"><i class="fa fa-check"></i><b>4.2</b> Lists</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="data-structures.html"><a href="data-structures.html#creating-a-list-of-vectors"><i class="fa fa-check"></i><b>4.2.1</b> Creating a list of vectors</a></li>
<li class="chapter" data-level="4.2.2" data-path="data-structures.html"><a href="data-structures.html#accessing-elements-in-the-list"><i class="fa fa-check"></i><b>4.2.2</b> Accessing elements in the list</a></li>
<li class="chapter" data-level="4.2.3" data-path="data-structures.html"><a href="data-structures.html#adding-items-to-lists"><i class="fa fa-check"></i><b>4.2.3</b> Adding items to lists</a></li>
<li class="chapter" data-level="4.2.4" data-path="data-structures.html"><a href="data-structures.html#labeling-items-within-lists"><i class="fa fa-check"></i><b>4.2.4</b> Labeling items within lists</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="data-structures.html"><a href="data-structures.html#matrices"><i class="fa fa-check"></i><b>4.3</b> Matrices</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="data-structures.html"><a href="data-structures.html#creating-a-matrix"><i class="fa fa-check"></i><b>4.3.1</b> Creating a matrix</a></li>
<li class="chapter" data-level="4.3.2" data-path="data-structures.html"><a href="data-structures.html#navigating-the-matrix"><i class="fa fa-check"></i><b>4.3.2</b> Navigating the matrix</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="data-structures.html"><a href="data-structures.html#dataframes"><i class="fa fa-check"></i><b>4.4</b> Dataframes</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="data-structures.html"><a href="data-structures.html#creating-a-dataframe"><i class="fa fa-check"></i><b>4.4.1</b> Creating a dataframe</a></li>
<li class="chapter" data-level="4.4.2" data-path="data-structures.html"><a href="data-structures.html#using-the-a-dataframe"><i class="fa fa-check"></i><b>4.4.2</b> Using the a dataframe</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="data-structures.html"><a href="data-structures.html#factors"><i class="fa fa-check"></i><b>4.5</b> Factors</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="data-wrangling.html"><a href="data-wrangling.html"><i class="fa fa-check"></i><b>5</b> Data Wrangling</a>
<ul>
<li class="chapter" data-level="5.1" data-path="data-wrangling.html"><a href="data-wrangling.html#r-packages"><i class="fa fa-check"></i><b>5.1</b> R Packages</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="data-wrangling.html"><a href="data-wrangling.html#installing-packages"><i class="fa fa-check"></i><b>5.1.1</b> Installing Packages</a></li>
<li class="chapter" data-level="5.1.2" data-path="data-wrangling.html"><a href="data-wrangling.html#using-packages"><i class="fa fa-check"></i><b>5.1.2</b> Using Packages</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="data-wrangling.html"><a href="data-wrangling.html#dplyr"><i class="fa fa-check"></i><b>5.2</b> dplyr</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="data-wrangling.html"><a href="data-wrangling.html#pipe-function"><i class="fa fa-check"></i><b>5.2.1</b> Pipe function (%&gt;%)</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="data-wrangling.html"><a href="data-wrangling.html#loading-datasets"><i class="fa fa-check"></i><b>5.3</b> Loading datasets</a></li>
<li class="chapter" data-level="5.4" data-path="data-wrangling.html"><a href="data-wrangling.html#understanding-your-dataset"><i class="fa fa-check"></i><b>5.4</b> Understanding your dataset</a></li>
<li class="chapter" data-level="5.5" data-path="data-wrangling.html"><a href="data-wrangling.html#combining-your-dataset"><i class="fa fa-check"></i><b>5.5</b> Combining your dataset</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="data-wrangling.html"><a href="data-wrangling.html#binds"><i class="fa fa-check"></i><b>5.5.1</b> Binds</a></li>
<li class="chapter" data-level="5.5.2" data-path="data-wrangling.html"><a href="data-wrangling.html#joins"><i class="fa fa-check"></i><b>5.5.2</b> Joins</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="data-wrangling.html"><a href="data-wrangling.html#missing-values"><i class="fa fa-check"></i><b>5.6</b> Missing values</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="data-exploration.html"><a href="data-exploration.html"><i class="fa fa-check"></i><b>6</b> Data Exploration</a>
<ul>
<li class="chapter" data-level="6.1" data-path="data-exploration.html"><a href="data-exploration.html#summary-statistics"><i class="fa fa-check"></i><b>6.1</b> Summary statistics</a></li>
<li class="chapter" data-level="6.2" data-path="data-exploration.html"><a href="data-exploration.html#standard-deviation-and-variance"><i class="fa fa-check"></i><b>6.2</b> Standard deviation and variance</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="data-exploration.html"><a href="data-exploration.html#standard-deviation"><i class="fa fa-check"></i><b>6.2.1</b> Standard deviation</a></li>
<li class="chapter" data-level="6.2.2" data-path="data-exploration.html"><a href="data-exploration.html#varience"><i class="fa fa-check"></i><b>6.2.2</b> Varience</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="data-visualization.html"><a href="data-visualization.html"><i class="fa fa-check"></i><b>7</b> Data visualization</a>
<ul>
<li class="chapter" data-level="7.1" data-path="data-visualization.html"><a href="data-visualization.html#plots"><i class="fa fa-check"></i><b>7.1</b> Plots</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="data-visualization.html"><a href="data-visualization.html#boxplots"><i class="fa fa-check"></i><b>7.1.1</b> Boxplots</a></li>
<li class="chapter" data-level="7.1.2" data-path="data-visualization.html"><a href="data-visualization.html#histogram"><i class="fa fa-check"></i><b>7.1.2</b> Histogram</a></li>
<li class="chapter" data-level="7.1.3" data-path="data-visualization.html"><a href="data-visualization.html#scatterplots"><i class="fa fa-check"></i><b>7.1.3</b> Scatterplots</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="data-visualization.html"><a href="data-visualization.html#ggplot2"><i class="fa fa-check"></i><b>7.2</b> ggplot2</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="data-visualization.html"><a href="data-visualization.html#boxplot"><i class="fa fa-check"></i><b>7.2.1</b> Boxplot</a></li>
<li class="chapter" data-level="7.2.2" data-path="data-visualization.html"><a href="data-visualization.html#histogram-1"><i class="fa fa-check"></i><b>7.2.2</b> Histogram</a></li>
<li class="chapter" data-level="7.2.3" data-path="data-visualization.html"><a href="data-visualization.html#scatterplot"><i class="fa fa-check"></i><b>7.2.3</b> Scatterplot</a></li>
<li class="chapter" data-level="7.2.4" data-path="data-visualization.html"><a href="data-visualization.html#exporting-plots"><i class="fa fa-check"></i><b>7.2.4</b> Exporting plots</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="data-visualization.html"><a href="data-visualization.html#gtsummary"><i class="fa fa-check"></i><b>7.3</b> gtsummary</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>8</b> Regression</a>
<ul>
<li class="chapter" data-level="8.1" data-path="regression.html"><a href="regression.html#linear-regression"><i class="fa fa-check"></i><b>8.1</b> Linear regression</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="regression.html"><a href="regression.html#assumptions-of-linear-regression"><i class="fa fa-check"></i><b>8.1.1</b> Assumptions of Linear Regression</a></li>
<li class="chapter" data-level="8.1.2" data-path="regression.html"><a href="regression.html#residuals"><i class="fa fa-check"></i><b>8.1.2</b> Residuals</a></li>
<li class="chapter" data-level="8.1.3" data-path="regression.html"><a href="regression.html#creating-our-intial-model"><i class="fa fa-check"></i><b>8.1.3</b> Creating our intial model</a></li>
<li class="chapter" data-level="8.1.4" data-path="regression.html"><a href="regression.html#interpretation-of-results"><i class="fa fa-check"></i><b>8.1.4</b> Interpretation of results</a></li>
<li class="chapter" data-level="8.1.5" data-path="regression.html"><a href="regression.html#assumption-checking"><i class="fa fa-check"></i><b>8.1.5</b> Assumption checking</a></li>
<li class="chapter" data-level="8.1.6" data-path="regression.html"><a href="regression.html#summary"><i class="fa fa-check"></i><b>8.1.6</b> Summary</a></li>
<li class="chapter" data-level="8.1.7" data-path="regression.html"><a href="regression.html#next-steps"><i class="fa fa-check"></i><b>8.1.7</b> Next steps</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="other-capabilties.html"><a href="other-capabilties.html"><i class="fa fa-check"></i><b>9</b> Other capabilties</a>
<ul>
<li class="chapter" data-level="9.1" data-path="other-capabilties.html"><a href="other-capabilties.html#r-bookdown"><i class="fa fa-check"></i><b>9.1</b> R-bookdown</a></li>
<li class="chapter" data-level="9.2" data-path="other-capabilties.html"><a href="other-capabilties.html#r-shiny"><i class="fa fa-check"></i><b>9.2</b> R-Shiny</a></li>
<li class="chapter" data-level="9.3" data-path="other-capabilties.html"><a href="other-capabilties.html#r-markdown"><i class="fa fa-check"></i><b>9.3</b> R-markdown</a></li>
<li class="chapter" data-level="9.4" data-path="other-capabilties.html"><a href="other-capabilties.html#machine-learning"><i class="fa fa-check"></i><b>9.4</b> Machine learning</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"><p><img src="RStudio-Logo-Flat.png" style="width:2in" /><br />
Intro to R Workshop</p></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="regression" class="section level1 hasAnchor" number="8">
<h1><span class="header-section-number">Chapter 8</span> Regression<a href="regression.html#regression" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>R is a statistical computing language which is capable of performing multiple statistical models including</p>
<ul>
<li><p>lm(y ~ x) linear regression model with one explanatory variable</p></li>
<li><p>lm(y ~ x1 + x2 + x3) multiple regression, a linear model with multiple explanatory variables</p></li>
<li><p>glm(y ~ x, family = poisson) generalized linear model, poisson distribution; see ?family to see those supported, including binomial, gaussian, poisson, etc.</p></li>
<li><p>glm(y ~ x + y, family = binomial) glm for logistic regression</p></li>
<li><p>aov(y ~ x) analysis of variance (same as lm except in the summary)</p></li>
<li><p>gam(y ~ x) generalized additive models</p></li>
<li><p>tree(y ~ x) or rpart(y ~ x) regression/classification trees</p></li>
</ul>
<div id="linear-regression" class="section level2 hasAnchor" number="8.1">
<h2><span class="header-section-number">8.1</span> Linear regression<a href="regression.html#linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Linear regression is a statistical method used for predictive analysis where we want to show if there is a linear relationship between an <strong>independent predictor</strong> variable and a <strong>dependent output</strong> variable. The goal is to build a mathematical formula that defines y as a function of the x variable. Once, we built a statistically significant model, it’s possible to use it for predicting future outcome on the basis of new x values.</p>
<p>From the previous scatterplot, we noticed that there might be a relationship between the years and arrivals for Sweden. We can try to perform a linear regression to determine if that is the case. The hypothesis we want to propose is that the number of arrivals to Sweden increases linearly per year.</p>
<p>The general formula for a linear model is</p>
<p><span class="math display">\[Y_{i} = \beta_{0} + \beta_{1}X_{1} + \epsilon \]</span>
where</p>
<p><span class="math display">\[Y_{i} = \text{Dependent Variable}\]</span>
<span class="math display">\[\beta_{0} = \text{Constant/Intercept}\]</span>
<span class="math display">\[\beta_{1} = \text{Slope/Intercept}\]</span>
<span class="math display">\[X_{1} = \text{Independent Variable}\]</span>
<span class="math display">\[\epsilon = \text{Error Term}\]</span></p>
<p>For our model, we would write out our linear regression equation as</p>
<p><span class="math display">\[\text{arrivals} = \beta_{0} + \beta_{1}*\text{Years} + \epsilon\]</span></p>
<div id="assumptions-of-linear-regression" class="section level3 hasAnchor" number="8.1.1">
<h3><span class="header-section-number">8.1.1</span> Assumptions of Linear Regression<a href="regression.html#assumptions-of-linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Before we begin with linear regression, there are some assumptions that need to be satisfied. We can use the <code>LINE</code> acronym to explain these assumptions.</p>
<ul>
<li><p><strong>L</strong>inearity of residuals - There needs to be a linear relationship between the dependent and independent variables(s)</p></li>
<li><p><strong>I</strong>ndependance of residuals - The error terms should not be dependent on one another. For example, in time series, the next value is dependent on the previous one.</p></li>
<li><p><strong>N</strong>ormal distribution of residuals - The mean residuals should follow a normal distribution with a mean equal to zero or close to zero.</p></li>
<li><p><strong>E</strong>qual variance of the residuals - The error terms must have constant variance</p></li>
</ul>
</div>
<div id="residuals" class="section level3 hasAnchor" number="8.1.2">
<h3><span class="header-section-number">8.1.2</span> Residuals<a href="regression.html#residuals" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Residuals represent the difference between the predicted value and the observed value. The formula for residuals is.</p>
<p><span class="math display">\[\text{Residual} - \text{actual y value} - \text{predicted y value}\]</span>
This is what residuals look like on a linear regression plot.</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-22"></span>
<img src="images/residuals2.png" alt="Residuals on a linear regression" width="558" />
<p class="caption">
Figure 8.1: Residuals on a linear regression
</p>
</div>
</div>
<div id="creating-our-intial-model" class="section level3 hasAnchor" number="8.1.3">
<h3><span class="header-section-number">8.1.3</span> Creating our intial model<a href="regression.html#creating-our-intial-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To create a linear model, we use this function when we have one explanatory variable</p>
<blockquote>
<p><strong>lm([target] ~ [predictor / features], data = [data source])</strong></p>
</blockquote>
<p>In this case our y-variable is the number of <code>arrivals</code> and the x-variable is the <code>years</code></p>
<h3>
Note:
</h3>
<blockquote>
<p>The years variable in our dataframe is a <em>character</em>. We need to convert it to a numeric to perform the linear regression.</p>
</blockquote>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="regression.html#cb111-1" aria-hidden="true" tabindex="-1"></a>swe_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(arrivals<span class="sc">~</span><span class="fu">as.numeric</span>(sweden_travel<span class="sc">$</span>years),<span class="at">data=</span>sweden_travel)</span>
<span id="cb111-2"><a href="regression.html#cb111-2" aria-hidden="true" tabindex="-1"></a>swe_model</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = arrivals ~ as.numeric(sweden_travel$years), data = sweden_travel)
## 
## Coefficients:
##                     (Intercept)  as.numeric(sweden_travel$years)  
##                      -470402333                           237113</code></pre>
</div>
<div id="interpretation-of-results" class="section level3 hasAnchor" number="8.1.4">
<h3><span class="header-section-number">8.1.4</span> Interpretation of results<a href="regression.html#interpretation-of-results" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can print out a summary of our model using the <strong>summary( )</strong> function. This will give us information on the intercept, standard error, p-value, test-statistic, <span class="math inline">\(r^2\)</span> value.</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="regression.html#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(swe_model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = arrivals ~ as.numeric(sweden_travel$years), data = sweden_travel)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -6608564  -826391  -507921   -40090  5703338 
## 
## Coefficients:
##                                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                     -470402333  126815668  -3.709  0.00109 ** 
## as.numeric(sweden_travel$years)     237113      63170   3.754  0.00098 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2416000 on 24 degrees of freedom
## Multiple R-squared:  0.3699, Adjusted R-squared:  0.3436 
## F-statistic: 14.09 on 1 and 24 DF,  p-value: 0.0009798</code></pre>
<p>In this output, the estimate column shows the estimates of our beta coefficients <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>.
The intercept (<span class="math inline">\(\beta_0\)</span>) is -470,402,333 and the coefficient of years variable is 237,113. We can rewrite our original equation with our new results</p>
<p><span class="math display">\[\text{arrivals} = \beta_{0} + \beta_{1}*\text{Years} + \epsilon\]</span>
<span class="math display">\[\text{arrivals} = -470,402,333 + 237,113*\text{Years} + \epsilon\]</span>
In writen form, we would say</p>
<ul>
<li><p>If the Years is equal to zero, we can expect -470,402,333 arrivals</p></li>
<li><p>For every 1 increase in Years, we can expect 237,113 arrivals</p></li>
</ul>
<p>The first point doesn’t make any sense since we can’t have year equal to 0.</p>
</div>
<div id="assumption-checking" class="section level3 hasAnchor" number="8.1.5">
<h3><span class="header-section-number">8.1.5</span> Assumption checking<a href="regression.html#assumption-checking" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>If we plot our linear regression, it will give us diagnostic plots that will help determine if our linear model satisfies certain assumptions</p>
<ul>
<li><p><strong>Residual vs Fitted</strong> - Used to check linear relationship assumptions.</p></li>
<li><p><strong>Normal Q-Q</strong>- Used to check if the residuals are normally distributed.</p></li>
<li><p><strong>Scale-Location</strong> - Used to check homogeneity of variance.</p></li>
<li><p><strong>Residuals vs Leverage</strong> - Used to check for influential cases or extreme values that might influence the regression results.</p></li>
</ul>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="regression.html#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(swe_model,<span class="at">which=</span>(<span class="dv">1</span>))</span></code></pre></div>
<p><img src="_main_files/figure-html/lm%20resdiual%20vs%20fitted%20plots-1.png" width="672" /></p>
<p>If our linearity assumption is met, we should see no pattern and the red line show be fairly flat. In our model, we see that this is the case with a few points cluster of points that lie above the line.</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="regression.html#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(swe_model,<span class="at">which=</span>(<span class="dv">2</span>))</span></code></pre></div>
<p><img src="_main_files/figure-html/lm%20normal%20q-q%20plots-1.png" width="672" /></p>
<p>For our normality assumption we can use the second plot, the Normal Q-Q plot. what we expect to see is a 45 degree line and most of the points should lie on this line. For our model this does not seem to hold true as our points are closer to a 10-20 degree slope.</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="regression.html#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(swe_model,<span class="at">which=</span>(<span class="dv">3</span>))</span></code></pre></div>
<p><img src="_main_files/figure-html/lm%20scale-location%20plots-1.png" width="672" /></p>
<p>To check our assumption of constant variance we can use the third plot, the scale-location plot. What we want to see here are points scattered randomly and the red line to be close to horizontal. However, what we see is there is a pattern and that indicates that the constant variance assumption does not hold true for this model. What we can try to do is transform our y variable using:</p>
<ul>
<li><p>Log transformation</p></li>
<li><p>Square Root transformation</p></li>
<li><p>Cube Root transformation</p></li>
</ul>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="regression.html#cb118-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb118-2"><a href="regression.html#cb118-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(swe_model, <span class="at">which=</span><span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">5</span>))</span></code></pre></div>
<p><img src="_main_files/figure-html/lm%20leverage-1.png" width="672" /></p>
<p>The last plot is the Residuals vs leverage plot. Leverage refers to to the extent where our coefficients would change if we removed an observation from the data set. Points that have high leverage would noticeably change our coefficients. If a point falls outside of the red dashed line, cook’s distance, it is considered to be a influential point and requires further investigation. For our model, we don’t have any points that are influential.</p>
</div>
<div id="summary" class="section level3 hasAnchor" number="8.1.6">
<h3><span class="header-section-number">8.1.6</span> Summary<a href="regression.html#summary" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Our initial hypothesis was</p>
<blockquote>
<p>Does the number of arrivals increase linearly over time (Years)?</p>
</blockquote>
<p>Since this model does not satisfy the normality assumption and the constant variance assumption that is required for linear regression, we cannot say that the number of arrivals increases linearly as years increases.</p>
</div>
<div id="next-steps" class="section level3 hasAnchor" number="8.1.7">
<h3><span class="header-section-number">8.1.7</span> Next steps<a href="regression.html#next-steps" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Since our linear regression model did not work, we can try using a different model that might be better in explaining trend. In this case, our independent variable is the number of arrivals which count data. Count data is data that does not contain any non-negative integer numbers, (0,1,2,3…). The usual function to deal with count data is a <code>Poisson Regression</code>, which is a generalized linear model used when the independent variable deals with count data that follows a Poisson distribution. It assumes the logarithm of expected values (mean) that can be modeled into a linear form by some unknown parameters.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="data-visualization.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="other-capabilties.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/07-linear-regression.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
